from .convolutional_sinkhorn import conv_sinkhorn
from .diffusion_emd import DiffusionCheb
from .diffusion_emd import DiffusionExact
from .diffusion_emd import DiffusionTree
from .diffusion_emd import DiffusionTreeV2
from .metric_tree import ClusterTree
from .metric_tree import MetricTree
from .metric_tree import QuadTree
from .version import __version__
