name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v2

      - name: Cache pre-commit
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}-
      - name: Run pre-commit
        id: precommit
        uses: pre-commit/action@v2.0.3
        continue-on-error: true

      - name: Commit files
        if: steps.precommit.outcome == 'failure'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: pre-commit

      - name: Check pre-commit
        if: steps.precommit.outcome == 'failure'
        uses: pre-commit/action@v2.0.0
